---

- name: Fail if required tandoor settings not defined
  ansible.builtin.fail:
    msg: >
      You need to define a required configuration setting (`{{ item }}`).
  when: "vars[item] == ''"
  with_items:
    - tandoor_identifier
    - tandoor_uid
    - tandoor_gid
    - tandoor_hostname
    - tandoor_path_prefix
    - tandoor_container_network

- when: tandoor_container_labels_traefik_enabled | bool
  block:
    - name: Fail if required tandoor Traefik settings not defined
      ansible.builtin.fail:
        msg: >-
          You need to define a required configuration setting (`{{ item }}`).
      when: "vars[item] == ''"
      with_items:
        - tandoor_container_labels_traefik_hostname
        - tandoor_container_labels_traefik_path_prefix

    # We ensure it doesn't end with a slash, because we handle both (slash and no-slash).
    # Knowing that `tandoor_container_labels_traefik_path_prefix` does not end with a slash
    # ensures we know how to set these routes up without having to do "does it end with a slash" checks elsewhere.
    - name: Fail if tandoor_container_labels_traefik_path_prefix ends with a slash
      ansible.builtin.fail:
        msg: >-
          tandoor_container_labels_traefik_path_prefix (`{{ tandoor_container_labels_traefik_path_prefix }}`) must either be `/` or not end with a slash (e.g. `/tandoor`).
      when: "tandoor_container_labels_traefik_path_prefix != '/' and tandoor_container_labels_traefik_path_prefix[-1] == '/'"

    # - name: Fail if tandoor_container_labels_traefik_path_prefix is not empty
    #   ansible.builtin.fail:
    #     msg: "tandoor_container_labels_traefik_path_prefix is not / -> tandoor_path_prefix has to be empty"
    #   when: tandoor_container_labels_traefik_path_prefix != "/"
        
